### ISSUE TITLE
Chrome Extension Disk Space error

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#46]
Impact: Screen shares from the Chrome extension 

Steps to Reproduce: 
1. Share your screen privately (entire screen mode) using Stage extension https://stage.screenleap.com/browser-share
2. Have a viewer connect to session from another computer
3. Open Performance tab of Task manager (Windows) or Apple menu > About this Mac > Storage tab (Mac) to see disk usage statistics. Free space dwindles over time until screen share crashes -- usually not more than 15 minutes into session

**Comment by tuyentruong** [comment]
This is caused by the Native Client library swapping to disk excessively. You can see the swap files being created when the Native Client library is enabled at /var/vm. From testing, it looks like the data that is posted to the library doesn't get cleaned up until there is a long period of inactivity. Reverting to not use Native Client library until a fix is found for this.

**Comment by tuyentruong** [comment]
Filed with Chromium project under https://bugs.chromium.org/p/chromium/issues/detail?id=600183#c3

**Comment by tuyentruong** [comment]
Fixed for now by reverting to using clipping diff algorithm instead of Native Client module.
