### ISSUE TITLE
Ubuntu/Chrome defaults to Java applet when clicking 'Share your Screen now'

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#53]
Steps to Reproduce:
1. Turn on User-Agent Switcher extension in Chrome and set it to either the 'Chrome on Ubuntu' option provided, or enter the following as user agent string: 
   Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
2. Go to www.screenleap.com and click 'Share your screen now'
3. Get re-directed to http://www.screenleap.com/troubleshooting-java?check=true instead of the expected Browser Share extension installation page 

Workaround: Go to http://www.screenleap.com/browser-share and 'Add to Chrome' . Extension can be added, signed into, and used to share without encountering any issues

**Comment by tuyentruong** [comment]
From looking at the support email, it sounds like the Chrome extension is being used for him. It's just that it was sharing only the browser window and not the entire screen. Can you confirm with him?

Using the user agent switcher to simulate Chrome on Ubuntu doesn't work because we use the navigator.platform property, which user agent switcher doesn't override.

**Comment by tuyentruong** [comment]
@LeahW Can you test to see if this is still an issue?

**Comment by LeahW** [comment]
This issue has been fixed; it now re-directs to the extension installation page when trying a new screen share from Chromebook
